# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-14 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myusername', models.CharField(max_length=250)),
                ('birth_year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Life_Profile',
                'verbose_name_plural': 'Life_Profiles',
            },
        ),
    ]
