# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-26 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeprofile',
            name='birth_year',
            field=models.DateField(auto_now=True),
        ),
    ]
