# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_quest', '0002_lifeprofile_smoking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeprofile',
            name='smoking',
            field=models.BooleanField(default=True),
        ),
    ]
