# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-27 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_quest', '0005_auto_20190126_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_method', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lifeprofile',
            name='calc_result',
            field=models.IntegerField(default=0),
        ),
    ]
