# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-12 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsribers',
            new_name='Subscribers',
        ),
    ]
